// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $film_id_ from "./routes/film/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $Filters from "./islands/Filters.tsx";
import * as $MainPage from "./islands/MainPage.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/film/[id].tsx": $film_id_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Filters.tsx": $Filters,
    "./islands/MainPage.tsx": $MainPage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
